### PR TITLE
Added support for error handling

### LINKED ISSUE #13: Support error handling in responses
Currently, if some error occurs with the api request, the request waits for timeout to occur, that's not good.

So I propose we should return some error to describe the failure.

### PR DESCRIPTION
**Pull request by bhavyaagg**
Fixes #13 . @championswimmer

### CODE REVIEW

**Comment by abhishek97** [comment]
@bhavyaagg I think you should also add appropriate status to code as well to indicate error.

**Comment by bhavyaagg** [comment]
@abhishek97 Thank you for your suggestions. On it.

**Comment by bhavyaagg** [comment]
@abhishek97 What exactly do you mean by appropriate status?

**Comment by abhishek97** [comment]
Set appropriate http status code for the response.
The original rfc for response status codes : https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by bhavyaagg** [comment]
@abhishek97 but the error could have occurred for multiple reasons.

**Pull request merged**
