### PR TITLE
made table responsive

### LINKED ISSUE #410: Leaderboard isn't responsive and overflows out of div on mobile
Screenshot from 2020-06-24 11-49-49

### PR DESCRIPTION
**Pull request by rahgurung**
closes #410 

used the BS native class for the small screen which is even better.

### CODE REVIEW

**Comment by gurrrung** [comment]
@hereisnaman This is ready to be merged.

**Comment by hereisnaman** [comment]
> @hereisnaman This is ready to be merged.

add screenshots

**Comment by gurrrung** [comment]
Scrolled to left:
Screenshot from 2020-07-05 17-49-29


Scrolled to right:
Screenshot from 2020-07-05 17-49-39

**Comment by gurrrung** [comment]
review ping

**Pull request closed without merging**
